"""title is now required

Revision ID: 698edda8d489
Revises: cd1730f6559d
Create Date: 2017-08-09 14:17:47.192790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '698edda8d489'
down_revision = 'cd1730f6559d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posters', 'title',
               existing_type=sa.VARCHAR(length=400),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posters', 'title',
               existing_type=sa.VARCHAR(length=400),
               nullable=True)
    # ### end Alembic commands ###
