"""Add Poster model

Revision ID: b26756ac7225
Revises:
Create Date: 2017-08-08 15:06:59.785568

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b26756ac7225'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. load uuid module
    op.get_bind().execute(sa.text('CREATE EXTENSION IF NOT EXISTS "uuid-ossp";'))
    # 2. create posters table
    op.create_table('posters',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('title', sa.String(length=400), nullable=True),
    sa.Column('authors', sa.Text(), nullable=True),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('source_url', sa.String(length=400), nullable=False),
    sa.Column('download_url', sa.String(length=400), nullable=False),
    sa.Column('presented_at', sa.String(length=200), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posters')
    # ### end Alembic commands ###
