"""empty message

Revision ID: cd1730f6559d
Revises: 5e737138aae2
Create Date: 2017-08-08 19:02:56.327264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd1730f6559d'
down_revision = '5e737138aae2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posters', sa.Column('email', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posters', 'email')
    # ### end Alembic commands ###
